/**
 * Shared Utilities - Clean Architecture
 * Common utilities used across all domains
 */

// Core utilities
// ================================================
// UNIFIED SHARED UTILITIES INDEX
// ================================================
// Central export hub for all shared utilities

// Import specific functions and objects
import {
  formatDate,
  formatDateTime,
  formatRelativeTime,
  isValidDate,
  addDays,
  addMonths,
  addYears,
  differenceInDays,
  differenceInHours,
  differenceInMinutes,
  startOfDay,
  endOfDay,
  startOfWeek,
  endOfWeek,
  startOfMonth,
  endOfMonth,
  isSameDay,
  isToday,
  isYesterday,
  isTomorrow,
  getTurkishDayName,
  getTurkishMonthName,
  isWeekend,
  addBusinessDays,
  calculateAge,
  parseTime,
  DateUtils,
} from './date';

import {
  slugify,
  truncateText,
  capitalizeFirst,
  capitalizeWords,
  capitalize,
  camelToKebab,
  kebabToCamel,
  camelToSnake,
  snakeToCamel,
  removeHtmlTags,
  removeHTML,
  escapeHTML,
  unescapeHTML,
  formatCurrency,
  formatNumber,
  formatBytes,
  formatPercentage,
  formatCompactNumber,
  extractInitials,
  formatPhoneNumber,
  formatEmailDomain,
  formatCreditCard,
  maskString,
  isValidEmail as formatIsValidEmail,
  isValidPhone as formatIsValidPhone,
  isValidUrl as formatIsValidUrl,
  removeExtraSpaces,
  reverseString,
  shuffleString,
  getWordCount,
  getCharacterCount,
  FormatUtils,
} from './format';

import {
  isEmail,
  isValidEmail,
  isPhone,
  isPhoneNumber,
  isTurkishMobile,
  isTurkishLandline,
  isURL,
  isUrl,
  isValidUrl,
  isHttpsUrl as validationIsHttpsUrl,
  isStrongPassword,
  validatePasswordStrength,
  isValidTurkishId,
  isValidTurkishID,
  isNumeric,
  isInteger as validationIsInteger,
  isPositive,
  isNegative,
  isInRange,
  validateRequired,
  validateEmail,
  validatePhoneNumber,
  validatePassword,
  validateMinLength,
  validateMaxLength,
  validateRange,
  validateFileSize,
  validateFileType,
  isNumber as validationIsNumber,
  isString as validationIsString,
  isBoolean as validationIsBoolean,
  isArray as validationIsArray,
  isObject as validationIsObject,
  isFunction as validationIsFunction,
  isDate as validationIsDate,
  isNull as validationIsNull,
  isUndefined as validationIsUndefined,
  isNullOrUndefined as validationIsNullOrUndefined,
  isEmpty,
  isNotEmpty,
  hasValue,
  sanitizeInput,
  isAlphaNumeric,
  isAlpha,
  hasSpecialChars,
  containsOnlyLettersAndSpaces,
  isValidCreditCard,
  getCreditCardType,
  isValidIBAN,
  ValidationUtils,
} from './validation';

import {
  isString,
  isNumber,
  isBoolean,
  isArray,
  isObject,
  isFunction,
  isDate,
  isNull,
  isUndefined,
  isNullOrUndefined,
  isInteger,
  isFloat,
  isPositiveNumber,
  isNegativeNumber,
  isNonEmptyString,
  isNumericString,
  isArrayOf,
  isStringArray,
  isNumberArray,
  isBooleanArray,
  isNonEmptyArray,
  hasProperty,
  hasProperties,
  isObjectWithKeys,
  isRecord,
  isEmptyObject,
  isNonEmptyObject,
  isJobBudgetObject,
  isValidJobBudget,
  isEmail as typeGuardIsEmail,
  isUrl as typeGuardIsUrl,
  isHttpsUrl,
  isValidPhone,
  isValidTurkishId as typeGuardIsValidTurkishId,
  isValidPassword,
  isFile,
  isImageFile,
  isDocumentFile,
  isError,
  isErrorWithMessage,
  isPromise,
  formatJobBudget,
  getBudgetType,
  getBudgetAmount,
  getBudgetRange,
  TypeGuards,
} from './typeGuards';

import {
  ALLOWED_FILE_TYPES,
  formatFileSize,
  getFileIcon,
  isFileTypeAllowed,
  isFileSizeValid,
  createFileAttachment,
  validateFiles,
} from './fileUpload';

import {
  debounce,
  debounceAsync,
  throttle,
  throttleAsync,
  retry,
  retryWithCircuitBreaker,
  withTimeout,
  withAbortController,
  batchAsync,
  parallelLimit,
  sleep,
  delay,
  promisify,
  promiseAllSettled,
  promiseMap,
  catchAsync,
  asyncTryCatch,
  memoizeAsync,
  AsyncUtils,
} from './async';

// ================================================
// RE-EXPORT ALL UTILITIES
// ================================================

// Date utilities
export {
  formatDate,
  formatDateTime,
  formatRelativeTime,
  isValidDate,
  addDays,
  addMonths,
  addYears,
  differenceInDays,
  differenceInHours,
  differenceInMinutes,
  startOfDay,
  endOfDay,
  startOfWeek,
  endOfWeek,
  startOfMonth,
  endOfMonth,
  isSameDay,
  isToday,
  isYesterday,
  isTomorrow,
  getTurkishDayName,
  getTurkishMonthName,
  isWeekend,
  addBusinessDays,
  calculateAge,
  parseTime,
  DateUtils,
};

// Format utilities
export {
  slugify,
  truncateText,
  capitalizeFirst,
  capitalizeWords,
  capitalize,
  camelToKebab,
  kebabToCamel,
  camelToSnake,
  snakeToCamel,
  removeHtmlTags,
  removeHTML,
  escapeHTML,
  unescapeHTML,
  formatCurrency,
  formatNumber,
  formatBytes,
  formatPercentage,
  formatCompactNumber,
  extractInitials,
  formatPhoneNumber,
  formatEmailDomain,
  formatCreditCard,
  maskString,
  formatIsValidEmail,
  formatIsValidPhone,
  formatIsValidUrl,
  removeExtraSpaces,
  reverseString,
  shuffleString,
  getWordCount,
  getCharacterCount,
  FormatUtils,
};

// Validation utilities
export {
  isEmail,
  isValidEmail,
  isPhone,
  isPhoneNumber,
  isTurkishMobile,
  isTurkishLandline,
  isURL,
  isUrl,
  isValidUrl,
  validationIsHttpsUrl,
  isStrongPassword,
  validatePasswordStrength,
  isValidTurkishId,
  isValidTurkishID,
  isNumeric,
  validationIsInteger,
  isPositive,
  isNegative,
  isInRange,
  validateRequired,
  validateEmail,
  validatePhoneNumber,
  validatePassword,
  validateMinLength,
  validateMaxLength,
  validateRange,
  validateFileSize,
  validateFileType,
  validationIsNumber,
  validationIsString,
  validationIsBoolean,
  validationIsArray,
  validationIsObject,
  validationIsFunction,
  validationIsDate,
  validationIsNull,
  validationIsUndefined,
  validationIsNullOrUndefined,
  isEmpty,
  isNotEmpty,
  hasValue,
  sanitizeInput,
  isAlphaNumeric,
  isAlpha,
  hasSpecialChars,
  containsOnlyLettersAndSpaces,
  isValidCreditCard,
  getCreditCardType,
  isValidIBAN,
  ValidationUtils,
};

// Type guards
export {
  isString,
  isNumber,
  isBoolean,
  isArray,
  isObject,
  isFunction,
  isDate,
  isNull,
  isUndefined,
  isNullOrUndefined,
  isInteger,
  isFloat,
  isPositiveNumber,
  isNegativeNumber,
  isNonEmptyString,
  isNumericString,
  isArrayOf,
  isStringArray,
  isNumberArray,
  isBooleanArray,
  isNonEmptyArray,
  hasProperty,
  hasProperties,
  isObjectWithKeys,
  isRecord,
  isEmptyObject,
  isNonEmptyObject,
  isJobBudgetObject,
  isValidJobBudget,
  typeGuardIsEmail,
  typeGuardIsUrl,
  isHttpsUrl,
  isValidPhone,
  typeGuardIsValidTurkishId,
  isValidPassword,
  isFile,
  isImageFile,
  isDocumentFile,
  isError,
  isErrorWithMessage,
  isPromise,
  formatJobBudget,
  getBudgetType,
  getBudgetAmount,
  getBudgetRange,
  TypeGuards,
};

// Async utilities
export {
  debounce,
  debounceAsync,
  throttle,
  throttleAsync,
  retry,
  retryWithCircuitBreaker,
  withTimeout,
  withAbortController,
  batchAsync,
  parallelLimit,
  sleep,
  delay,
  promisify,
  promiseAllSettled,
  promiseMap,
  catchAsync,
  asyncTryCatch,
  memoizeAsync,
  AsyncUtils,
};

// File upload utilities
export {
  ALLOWED_FILE_TYPES,
  formatFileSize,
  getFileIcon,
  isFileTypeAllowed,
  isFileSizeValid,
  createFileAttachment,
  validateFiles,
};

// ================================================
// COMMONLY USED UTILITIES (CONVENIENCE OBJECT)
// ================================================

export const utils = {
  // Date
  formatDate,
  formatRelativeTime,
  isToday,
  addDays,
  calculateAge,

  // Format
  slugify,
  truncateText,
  capitalizeFirst,
  formatCurrency,
  formatBytes,

  // Validation
  isEmail,
  isEmpty,
  validateRequired,
  sanitizeInput,

  // Type guards
  isString,
  isNumber,
  isArray,
  isObject,

  // Async
  debounce,
  throttle,
  sleep,
  retry,
  withTimeout,
};

// ================================================
// COMBINED UTILITY NAMESPACES
// ================================================
export const SharedUtils = {
  DateUtils,
  FormatUtils,
  ValidationUtils,
  TypeGuards,
  AsyncUtils,

  // Convenience access
  utils,
};

// Legacy compatibility
export * from '../utils';
