import { Category } from '@/types/business/features/marketplace-categories';

// ==========================================
// MARKETPLACE CATEGORIES DATA
// ==========================================
// 16 Main Categories with 800+ Services

export const MARKETPLACE_CATEGORIES: Category[] = [
  // 1. TEKNOLOJİ & YAZILIM
  {
    id: 'teknoloji-yazilim',
    title: 'Teknoloji & Yazılım',
    description:
      'Web geliştirme, mobil uygulama, yazılım çözümleri ve teknoloji danışmanlığı hizmetleri',
    shortDescription: 'Web, mobil ve yazılım geliştirme',
    icon: 'Code',
    iconColor: '#3B82F6', // Blue-500
    serviceCount: 200, // 85+45+35+20+15 = 200
    averagePrice: 2500,
    priceRange: { min: 500, max: 15000 },
    topSkills: ['React', 'Node.js', 'Python', 'Mobil Uygulama', 'WordPress'],
    popularServices: [
      'Web Sitesi',
      'Mobil Uygulama',
      'E-ticaret',
      'API Geliştirme',
    ],
    trending: true,
    featured: true,
    order: 1,
    slug: 'teknoloji-yazilim',
    metadata: {
      seoTitle: 'Teknoloji & Yazılım Hizmetleri | MarifetBul',
      seoDescription:
        'Web geliştirme, mobil uygulama ve yazılım çözümleri için uzman geliştiriciler bulun.',
      keywords: [
        'web geliştirme',
        'mobil uygulama',
        'yazılım',
        'programlama',
        'teknoloji',
      ],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 1250,
      completedProjects: 8940,
      averageRating: 4.8,
      responseTime: 2,
      successRate: 95,
      monthlyGrowth: 12,
    },
    subcategories: [
      {
        id: 'web-gelistirme',
        name: 'Web Geliştirme',
        description: 'WordPress, React, Vue.js ile web sitesi geliştirme',
        serviceCount: 85,
        averagePrice: 3000,
        priceRange: { min: 800, max: 12000 },
        popularServices: [
          'WordPress Web Sitesi',
          'E-ticaret Sitesi',
          'Kurumsal Web Sitesi',
          'React.js Uygulaması',
          'Vue.js Geliştirme',
          'Next.js Projesi',
          'Açılış Sayfası',
          'Blog Sitesi',
          'Portfolyo Sitesi',
          'Restaurant Menü Sitesi',
          'Emlak Sitesi',
          'Online Eğitim Platformu',
          'Forum Sitesi',
          'Sosyal Medya Platformu',
          'CMS (İçerik Yönetim Sistemi)',
          'API Entegrasyonu',
          'Responsive Tasarım (Duyarlı)',
          'SEO Optimizasyonu',
          'Web Performans Optimizasyonu',
          'PWA (İlerleyici Web Uygulaması)',
          'Çok Dilli Web Sitesi',
          'Üyelik Sitesi',
          'Rezervasyon Sistemi',
          'Online Randevu Sistemi',
          'E-katalog Sitesi',
          'Haber Sitesi',
          'Online Galeri',
          'Etkinlik Yönetim Sitesi',
          'Emlak Portalı',
          'İş Portalı',
          'İlan Sitesi',
          'Online Rezervasyon Sistemi',
          'Müşteri Portalı',
          'Yönetim Paneli',
          'Web Tabanlı CRM',
          'Stok Yönetim Sistemi',
          'Online Ödeme Entegrasyonu',
          'Çok Satıcılı Pazaryeri',
          'SaaS Platformu',
          'Web Analitik Entegrasyonu',
          'Üçüncü Taraf API Entegrasyonu',
          'Veritabanı Taşıma',
          'Web Sitesi Yeniden Tasarım',
          'Web Sitesi Bakımı',
          'Hata Düzeltme ve Güncellemeler',
          'Güvenlik Uygulaması',
          'SSL Sertifikası Kurulumu',
          'Domain ve Hosting Kurulumu',
          'Web Sitesi Hız Optimizasyonu',
          'Mobil Optimizasyon',
          'Tarayıcılar Arası Uyumluluk',
          'Web Sitesi Yedekleme Çözümleri',
          'İçerik Yönetimi',
          'Kullanıcı Kimlik Doğrulama Sistemi',
          'E-posta Entegrasyonu',
          'Sosyal Medya Entegrasyonu',
          'Google Analytics Kurulumu',
          'Arama İşlevselliği',
          'İletişim Formları',
          'Haber Bülteni Entegrasyonu',
          'Canlı Sohbet Entegrasyonu',
          'Online Dokümantasyon',
          'Yardım Masası Sistemi',
          'Bilgi Bankası',
          'FAQ Sistemi (Sık Sorulan Sorular)',
          'İnceleme ve Değerlendirme Sistemi',
          'Bildirim Sistemi',
          'Dosya Yükleme Sistemi',
          'Resim Galerisi',
          'Video Entegrasyonu',
          'Harita Entegrasyonu',
          'Takvim Entegrasyonu',
          'Rezervasyon Takvimi',
          'Etkinlik Takvimi',
          'Proje Yönetim Aracı',
          'Görev Yönetim Sistemi',
          'Zaman Takip Sistemi',
          'Raporlama Panosu',
          'Veri Görselleştirme',
          'Grafik Entegrasyonu',
          'PDF/Excel Dışa Aktarma',
          'Yazdırma İşlevselliği',
          'Barkod/QR Kod Üretici',
          'Fatura Sistemi',
          'Online Hesap Makinesi',
          'Anket Sistemi',
          'Quiz Sistemi',
          'Sınav Sistemi',
          'Öğrenme Yönetim Sistemi',
          'Online Kurs Platformu',
          'Webinar Platformu',
          'Video Yayını',
        ],
        slug: 'web-gelistirme',
        parentCategoryId: 'teknoloji-yazilim',
      },
      {
        id: 'mobil-uygulama',
        name: 'Mobil Uygulama',
        description: 'iOS, Android ve cross-platform mobil uygulama geliştirme',
        serviceCount: 45,
        averagePrice: 4500,
        priceRange: { min: 2000, max: 15000 },
        popularServices: [
          'iOS Yerel Uygulama',
          'Android Yerel Uygulama',
          'React Native Uygulama',
          'Flutter Uygulama',
          'Ionic Uygulama',
          'Xamarin Uygulama',
          'İlerleyici Web Uygulaması',
          'Hibrit Mobil Uygulama',
          'E-ticaret Mobil Uygulama',
          'Sosyal Medya Uygulaması',
          'Mesajlaşma Uygulaması',
          'Oyun Uygulaması',
          'Fitness Takip Uygulaması',
          'Sağlık Uygulaması',
          'Eğitim Uygulaması',
          'Finans Uygulaması',
          'Bankacılık Uygulaması',
          'Seyahat Uygulaması',
          'Yemek Teslimat Uygulaması',
          'Taksi Uygulaması',
          'Arkadaşlık Uygulaması',
          'Müzik Yayın Uygulaması',
          'Video Yayın Uygulaması',
          'Haber Uygulaması',
          'Hava Durumu Uygulaması',
          'Yapılacaklar Listesi',
          'Takvim Uygulaması',
          'Not Alma Uygulaması',
          'Fotoğraf Düzenleme Uygulaması',
          'Kamera Uygulaması',
          'QR Kod Tarayıcı',
          'GPS Navigasyon Uygulaması',
          'AR Uygulaması (Artırılmış Gerçeklik)',
          'VR Uygulaması (Sanal Gerçeklik)',
          'IoT Kontrol Uygulaması',
          'Akıllı Ev Uygulaması',
          'Bluetooth Entegrasyonu',
          'NFC Entegrasyonu',
          'Barkod Tarayıcı',
          'Belge Tarayıcı',
          'Ses Kayıt Uygulaması',
          'Ses Çalar',
          'Video Oynatıcı',
          'Canlı Yayın Uygulaması',
          'Sohbet Botu Entegrasyonu',
        ],
        slug: 'mobil-uygulama',
        trending: true,
        parentCategoryId: 'teknoloji-yazilim',
      },
      {
        id: 'yazilim-gelistirme',
        name: 'Yazılım Geliştirme',
        description: 'Özel yazılım, API ve enterprise çözümler',
        serviceCount: 35,
        averagePrice: 5000,
        priceRange: { min: 1500, max: 20000 },
        popularServices: [
          'Özel Yazılım Geliştirme',
          'API Geliştirme',
          'Veritabanı Tasarımı',
          'Mikroservis Mimarisi',
          'Bulut Çözümleri',
          'DevOps Kurulumu',
          'CI/CD Pipeline (Sürekli Entegrasyon/Dağıtım)',
          'Kurumsal Yazılım',
          'ERP Sistemi (Kurumsal Kaynak Planlama)',
          'CRM Sistemi (Müşteri İlişkileri Yönetimi)',
          'Stok Yönetimi',
          'HR Yönetim Sistemi (İnsan Kaynakları)',
          'Proje Yönetim Aracı',
          'BI (İş Zekası)',
          'Veri Analiz Platformu',
          'Raporlama Sistemi',
          'Doküman Yönetimi',
          'İş Akışı Otomasyonu',
          'Eski Sistem Geçişi',
          'Sistem Entegrasyonu',
          'Üçüncü Taraf Entegrasyonları',
          'Ödeme Geçidi Entegrasyonu',
          'E-posta Pazarlama Platformu',
          'Müşteri Destek Sistemi',
          'Yardım Masası Yazılımı',
          'Bilgi Bankası Sistemi',
          'Rezervasyon Sistemi',
          'Rezervasyon Platformu',
          'Etkinlik Yönetim Sistemi',
          'İçerik Yönetim Sistemi',
          'LMS (Öğrenme Yönetim Sistemi)',
          'HMS (Hastane Yönetim Sistemi)',
          'SMS Sistemi (Okul Yönetim Sistemi)',
          'LMS (Kütüphane Yönetim Sistemi)',
          'POS Sistemi (Satış Noktası)',
        ],
        slug: 'yazilim-gelistirme',
        parentCategoryId: 'teknoloji-yazilim',
      },
      {
        id: 'siber-guvenlik',
        name: 'Siber Güvenlik',
        description:
          'Güvenlik testleri, penetration testing ve güvenlik danışmanlığı',
        serviceCount: 20,
        averagePrice: 3500,
        priceRange: { min: 1000, max: 10000 },
        popularServices: [
          'Sızma Testi',
          'Güvenlik Denetimi',
          'SSL Sertifikası Kurulumu',
          'Güvenlik Açığı Değerlendirmesi',
          'Güvenlik Kod İncelemesi',
          'Ağ Güvenliği',
          'Web Uygulama Güvenliği',
          'Mobil Uygulama Güvenliği',
          'Bulut Güvenliği',
          'Veri Şifreleme',
          'Güvenlik Duvarı Yapılandırması',
          'Saldırı Tespit Sistemi',
          'Güvenlik İzleme',
          'Olay Müdahale',
          'Dijital Adli Tıp',
          'Risk Değerlendirmesi',
          'Uyumluluk Denetimi',
          'Güvenlik Eğitimi',
          'Parola Politikası',
          'İki Faktörlü Kimlik Doğrulama',
        ],
        slug: 'siber-guvenlik',
        parentCategoryId: 'teknoloji-yazilim',
      },
      {
        id: 'blockchain',
        name: 'Blockchain & Kripto',
        description:
          'Smart contract, DeFi (Merkeziyetsiz Finans) ve blockchain uygulama geliştirme',
        serviceCount: 15,
        averagePrice: 6000,
        priceRange: { min: 2000, max: 25000 },
        popularServices: [
          'Akıllı Sözleşme Geliştirme',
          'DeFi Uygulaması',
          'NFT Pazaryeri',
          'Kripto Para Borsası',
          'Token Geliştirme',
          'ICO Platformu',
          'Blockchain Danışmanlığı',
          'Kripto Para Cüzdanı',
          'Solidity Geliştirme',
          'Ethereum DApp',
          'Bitcoin Entegrasyonu',
          'Binance Smart Chain',
          'Web3 Geliştirme',
          'DAO Geliştirme',
          'Yield Farming Platformu',
        ],
        slug: 'blockchain',
        trending: true,
        parentCategoryId: 'teknoloji-yazilim',
      },
    ],
  },

  // 2. TASARIM & KREATİF
  {
    id: 'tasarim-kreatif',
    title: 'Tasarım & Kreatif',
    description:
      'Grafik tasarım, UI/UX, logo, video editing ve kreatif çözümler',
    shortDescription: 'Grafik tasarım ve kreatif hizmetler',
    icon: 'Palette',
    iconColor: '#8B5CF6', // Purple-500
    serviceCount: 152, // 62+40+30+20 = 152
    averagePrice: 1800,
    priceRange: { min: 200, max: 8000 },
    topSkills: [
      'Photoshop',
      'Illustrator',
      'Figma',
      'After Effects',
      'Video Düzenleme',
    ],
    popularServices: [
      'Logo Tasarımı',
      'Web Tasarımı',
      'Video Düzenleme',
      'Sosyal Medya Tasarımı',
    ],
    trending: true,
    featured: true,
    order: 2,
    slug: 'tasarim-kreatif',
    metadata: {
      seoTitle: 'Tasarım & Kreatif Hizmetler | MarifetBul',
      seoDescription:
        'Logo, grafik tasarım, UI/UX ve video editing için profesyonel tasarımcılar.',
      keywords: [
        'grafik tasarım',
        'logo tasarımı',
        'ui ux',
        'video editing',
        'kreatif',
      ],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 980,
      completedProjects: 12500,
      averageRating: 4.7,
      responseTime: 1,
      successRate: 93,
      monthlyGrowth: 8,
    },
    subcategories: [
      {
        id: 'grafik-tasarim',
        name: 'Grafik Tasarım',
        description: 'Logo, poster, broşür ve kurumsal kimlik tasarımı',
        serviceCount: 62,
        averagePrice: 1200,
        priceRange: { min: 200, max: 5000 },
        popularServices: [
          'Logo Tasarımı',
          'Kurumsal Kimlik',
          'Poster Tasarımı',
          'Broşür Tasarımı',
          'Kartvizit Tasarımı',
          'Antetli Kağıt',
          'Zarf Tasarımı',
          'Katalog Tasarımı',
          'Dergi Tasarımı',
          'Kitap Kapağı',
          'CD/DVD Kapağı',
          'Ambalaj Tasarımı',
          'Etiket Tasarımı',
          'Banner Tasarımı',
          'Rollup Banner',
          'Billboard Tasarımı',
          'Araç Giydirme',
          'Tabela Tasarımı',
          'T-shirt Tasarımı',
          'Mug Tasarımı',
          'Takvim Tasarımı',
          'Ajanda Tasarımı',
          'Sertifika Tasarımı',
          'Diploma Tasarımı',
          'İnfografik',
          'İkon Tasarımı',
          'Pattern Tasarımı',
          'Duvar Kağıdı Tasarımı',
          'Sosyal Medya Kiti',
          'Marka Kılavuzu',
          'Kırtasiye Tasarımı',
          'Kartvizit Tasarımı',
          'Antetli Kağıt Tasarımı',
          'Fatura Tasarımı',
          'Sunum Tasarımı',
          'Slayt Şablonu',
          'PowerPoint Teması',
          'Rapor Tasarımı',
          'Menü Tasarımı',
          'El İlanı Tasarımı',
          'Davetiye Tasarımı',
          'Düğün Davetiyesi',
          'Etkinlik Posteri',
          'Konser Posteri',
          'Film Posteri',
          'Kitap Düzeni',
          'Dergi Düzeni',
          'Haber Bülteni Tasarımı',
          'E-posta Şablonu',
          'Web Banner',
          'Uygulama İkonu',
          'Favicon Tasarımı',
          'YouTube Küçük Resim',
          'Sosyal Medya Gönderisi',
          'Instagram Hikayesi',
          'Facebook Kapağı',
          'LinkedIn Banner',
          'Twitter Başlığı',
          'Basılı Reklam',
          'Dijital Reklam',
          'Vektör İllüstrasyon',
          'Karakter Tasarımı',
        ],
        slug: 'grafik-tasarim',
        parentCategoryId: 'tasarim-kreatif',
      },
      {
        id: 'ui-ux-tasarim',
        name: 'UI/UX Tasarım',
        description: 'Web ve mobil uygulama kullanıcı deneyimi tasarımı',
        serviceCount: 40,
        averagePrice: 2800,
        priceRange: { min: 800, max: 8000 },
        popularServices: [
          'Web Kullanıcı Arayüzü Tasarımı',
          'Mobil Uygulama Kullanıcı Deneyimi Tasarımı',
          'Prototip Tasarımı',
          'Tel Çerçeve Tasarımı',
          'Kullanıcı Yolculuğu Haritalama',
          'Kullanıcı Araştırması',
          'Kullanılabilirlik Testi',
          'Bilgi Mimarisi',
          'Etkileşim Tasarımı',
          'Görsel Tasarım',
          'Tasarım Sistemi',
          'Stil Kılavuzu',
          'Bileşen Kütüphanesi',
          'Açılış Sayfası Tasarımı',
          'Kontrol Paneli Tasarımı',
          'Yönetici Paneli Tasarımı',
          'E-ticaret Tasarımı',
          'SaaS Platform Tasarımı',
          'Mobil Öncelikli Tasarım',
          'Duyarlı Tasarım',
          'Erişilebilirlik Tasarımı',
          'Tasarım Denetimi',
          'Rakip Analizi',
          'Kullanıcı Profili Geliştirme',
          'Kullanıcı Akış Tasarımı',
          'Maket Tasarımı',
          'Yüksek Kaliteli Prototip',
          'Etkileşimli Prototip',
          'Figma Tasarımı',
          'Sketch Tasarımı',
          'Adobe XD Tasarımı',
          'InVision Prototip',
          'Prensip Animasyonu',
          'Mikro Etkileşimler',
          'Animasyon Tasarımı',
          'İkon Sistem Tasarımı',
          'Kullanıcı Arayüzü İçin İllüstrasyon',
          'Tasarım Teslimi',
          'Geliştirici İşbirliği',
          'Design Documentation',
        ],
        slug: 'ui-ux-tasarim',
        trending: true,
        parentCategoryId: 'tasarim-kreatif',
      },
      {
        id: 'video-animasyon',
        name: 'Video & Animasyon',
        description: '2D/3D animasyon, hareket grafikleri ve video düzenleme',
        serviceCount: 30,
        averagePrice: 2200,
        priceRange: { min: 500, max: 6000 },
        popularServices: [
          'Video Düzenleme',
          '2D Animasyon',
          'Hareket Grafikleri',
          '3D Animasyon',
          'Whiteboard Animasyonu',
          'Explainer Video',
          'Logo Animasyonu',
          'Intro/Outro Video',
          'YouTube Video Düzenleme',
          'Reklam Videosu',
          'Sosyal Medya Videosu',
          'Ürün Tanıtım Videosu',
          'Kurumsal Tanıtım Videosu',
          'Eğitim Videosu',
          'Sunum Videosu',
          'Müzik Videosu',
          'Kısa Film Düzenleme',
          'Belgesel Düzenleme',
          'Podcast Video Düzenleme',
          'Yeşil Ekran (Chroma Key)',
          'Renk Düzeltme (Color Grading)',
          'Ses Düzenleme',
          'Alt Yazı Ekleme',
          'Video Efektleri',
          'Geçiş Efektleri',
          'Drone Video Düzenleme',
          'Hızlandırılmış Video (Timelapse)',
          'Slow Motion Video',
          'Stop Motion Animasyon',
          'Karakter Animasyonu',
        ],
        slug: 'video-animasyon',
        parentCategoryId: 'tasarim-kreatif',
      },
      {
        id: 'fotograf',
        name: 'Fotoğraf & Retouch',
        description: 'Ürün fotoğrafçılığı, portre ve fotoğraf düzenleme',
        serviceCount: 20,
        averagePrice: 1500,
        priceRange: { min: 300, max: 4000 },
        popularServices: [
          'Ürün Fotoğrafçılığı',
          'Portre Fotoğrafçılığı',
          'Fotoğraf Rötuşu',
          'Arka Plan Kaldırma',
          'Renk Düzeltme',
          'Gölge Ekleme',
          'Fotoğraf Restorasyonu',
          'Beauty Retouching',
          'Gıda Fotoğrafçılığı',
          'Emlak Fotoğrafçılığı',
          'Moda Fotoğrafçılığı',
          'Etkinlik Fotoğrafçılığı',
          'Düğün Fotoğrafçılığı',
          'Stüdyo Çekimi',
          'Ürün 360° Çekim',
          'E-ticaret Fotoğraf',
          'Katalog Çekimi',
          'Lookbook Çekimi',
          'Hava Çekimi (Drone)',
          'Mimari Fotoğrafçılık',
        ],
        slug: 'fotograf',
        parentCategoryId: 'tasarim-kreatif',
      },
    ],
  },

  // 3. PAZARLAMA & REKLAM
  {
    id: 'pazarlama-reklam',
    title: 'Pazarlama & Reklam',
    description:
      'Dijital pazarlama, SEO, sosyal medya yönetimi ve reklam kampanyaları',
    shortDescription: 'Dijital pazarlama ve sosyal medya',
    icon: 'Megaphone',
    iconColor: '#10B981', // Green-500
    serviceCount: 120,
    averagePrice: 2200,
    priceRange: { min: 300, max: 10000 },
    topSkills: [
      'SEO',
      'Google Ads',
      'Sosyal Medya',
      'İçerik Pazarlama',
      'Analitik',
    ],
    popularServices: [
      'SEO Optimizasyonu',
      'Google Ads',
      'Sosyal Medya Yönetimi',
      'Content Marketing (İçerik Pazarlama)',
    ],
    trending: true,
    featured: true,
    order: 3,
    slug: 'pazarlama-reklam',
    metadata: {
      seoTitle: 'Pazarlama & Reklam Hizmetleri | MarifetBul',
      seoDescription:
        'SEO, Google Ads, sosyal medya ve dijital pazarlama uzmanları ile işinizi büyütün.',
      keywords: [
        'seo',
        'google ads',
        'sosyal medya',
        'dijital pazarlama',
        'reklam',
      ],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 850,
      completedProjects: 9800,
      averageRating: 4.6,
      responseTime: 3,
      successRate: 91,
      monthlyGrowth: 15,
    },
    subcategories: [
      {
        id: 'seo-sem',
        name: 'SEO & SEM',
        description: 'Arama motoru optimizasyonu ve Google Ads yönetimi',
        serviceCount: 45,
        averagePrice: 2800,
        priceRange: { min: 500, max: 8000 },
        popularServices: [
          'SEO Audit',
          'Google Ads Campaign',
          'Keyword Research',
          'On-Page SEO',
          'Off-Page SEO',
          'Technical SEO',
          'Local SEO',
          'E-commerce SEO',
          'Link Building',
          'Content SEO',
          'SEO Copywriting',
          'Google Analytics Setup',
          'Google Search Console',
          'Schema Markup',
          'Page Speed Optimization',
          'Mobile SEO',
          'Voice Search Optimization',
          'SEO Content Strategy',
          'Competitor Analysis',
          'SERP Analysis',
          'Backlink Analysis',
          'Google My Business',
          'YouTube SEO',
          'App Store Optimization',
          'Bing Reklamları',
          'Facebook Reklamları',
          'Instagram Reklamları',
          'LinkedIn Reklamları',
          'Twitter Reklamları',
          'Görüntülü Reklamcılık',
          'Yeniden Pazarlama Kampanyaları',
          'Alışveriş Reklamları',
          'Video Reklamcılık',
          'Açılış Sayfası Optimizasyonu',
          'Dönüşüm Oranı Optimizasyonu',
          'A/B Testi',
          'Google Tag Manager (GTM)',
          'Dönüşüm Takibi',
          'ROI Analizi (Yatırım Getirisi)',
          'PPC Yönetimi (Tıklama Başına Ödeme)',
          'Teklif Yönetimi',
          'Reklam Metni Yazarlığı',
          'Kampanya Optimizasyonu',
          'Performans Raporlama',
          'Pazarlama Otomasyonu',
        ],
        slug: 'seo-sem',
        parentCategoryId: 'pazarlama-reklam',
      },
      {
        id: 'sosyal-medya',
        name: 'Sosyal Medya',
        description:
          'Instagram, Facebook, LinkedIn hesap yönetimi ve içerik üretimi',
        serviceCount: 35,
        averagePrice: 1800,
        priceRange: { min: 300, max: 5000 },
        popularServices: [
          'Instagram Yönetimi',
          'İçerik Üretimi',
          'Sosyal Medya Stratejisi',
          'Facebook Yönetimi',
          'LinkedIn Yönetimi',
          'Twitter Yönetimi',
          'TikTok Yönetimi',
          'Pinterest Yönetimi',
          'YouTube Kanal Yönetimi',
          'Sosyal Medya İçerik Takvimi',
          'Hashtag Stratejisi',
          'Community Management',
          'Yorum Yönetimi',
          'Influencer İletişimi',
          'Sosyal Medya Görselleri',
          'Instagram Reels',
          'Instagram Stories',
          'Facebook Reklamları',
          'Instagram Reklamları',
          'LinkedIn Reklamları',
          'Twitter Reklamları',
          'TikTok Reklamları',
          'Sosyal Medya Analizi',
          'Rakip Analizi',
          'Takipçi Artırma Stratejisi',
          'Engagement Artırma',
          'Marka Bilinirliği',
          'Sosyal Medya Danışmanlığı',
          'Kriz Yönetimi',
          'İtibar Yönetimi',
          'Kullanıcı Türevli İçerik',
          'Yarışma ve Kampanya Yönetimi',
          'Canlı Yayın Yönetimi',
          'Sosyal Medya Eğitimi',
          'Sosyal Medya Politikası',
        ],
        slug: 'sosyal-medya',
        trending: true,
        parentCategoryId: 'pazarlama-reklam',
      },
      {
        id: 'content-marketing',
        name: 'İçerik Pazarlama',
        description: 'Blog yazarlığı, copywriting ve içerik stratejisi',
        serviceCount: 25,
        averagePrice: 1500,
        priceRange: { min: 200, max: 4000 },
        popularServices: [
          'Blog Yazarlığı',
          'Metin Yazarlığı',
          'E-posta Pazarlama',
          'Haber Bülteni Yazarlığı',
          'Makale Yazarlığı',
          'Ürün Açıklaması Yazarlığı',
          'Kategori Açıklaması',
          'Web Sitesi Metni',
          'Açılış Sayfası Metni',
          'Reklam Metni',
          'Basın Bülteni',
          'Vaka Çalışması',
          'Teknik Yazarlık',
          'E-kitap Yazarlığı',
          'Beyaz Kağıt (White Paper)',
          'İnfografik İçerik',
          'Video Senaryosu',
          'Podcast Senaryosu',
          'Sosyal Medya Metni',
          'E-posta Kampanyası',
          'İçerik Stratejisi',
          'İçerik Takvimi',
          'Editörlük',
          'Düzeltme',
          'SEO İçerik Yazarlığı',
        ],
        slug: 'content-marketing',
        parentCategoryId: 'pazarlama-reklam',
      },
      {
        id: 'influencer-marketing',
        name: 'Influencer Pazarlama',
        description: 'Influencer kampanya yönetimi ve işbirlikleri',
        serviceCount: 15,
        averagePrice: 3500,
        priceRange: { min: 1000, max: 10000 },
        popularServices: [
          'Influencer Kampanyası',
          'Marka Ortaklıkları',
          'İçerik İşbirlikleri',
          'Influencer Keşfi',
          'Influencer Vetting',
          'Kampanya Stratejisi',
          'Sözleşme Yönetimi',
          'İçerik Onay Süreci',
          'Performans Takibi',
          'ROI Analizi',
          'Mikro Influencer Kampanyaları',
          'Makro Influencer Kampanyaları',
          'Ürün Yerleştirme',
          'Sponsorlu İçerik',
          'Affiliate Marketing',
        ],
        slug: 'influencer-marketing',
        trending: true,
        parentCategoryId: 'pazarlama-reklam',
      },
    ],
  },

  // 4. EV & YAŞAM HİZMETLERİ
  {
    id: 'ev-yasam',
    title: 'Ev & Yaşam Hizmetleri',
    description: 'Tadilat, temizlik, nakliye ve ev bakım hizmetleri',
    shortDescription: 'Ev tadilat, temizlik ve bakım',
    icon: 'Home',
    iconColor: '#F59E0B', // Orange-500
    serviceCount: 280,
    averagePrice: 800,
    priceRange: { min: 100, max: 5000 },
    topSkills: ['Tadilat', 'Elektrik', 'Tesisatçılık', 'Boyacılık', 'Temizlik'],
    popularServices: ['Ev Temizliği', 'Boyacı', 'Elektrikçi', 'Tesisatçı'],
    trending: false,
    featured: true,
    order: 4,
    slug: 'ev-yasam',
    metadata: {
      seoTitle: 'Ev & Yaşam Hizmetleri | MarifetBul',
      seoDescription:
        'Tadilat, temizlik, elektrik, tesisatçı ve ev bakım hizmetleri için uzmanlar.',
      keywords: [
        'tadilat',
        'ev temizliği',
        'elektrikçi',
        'tesisatçı',
        'boyacı',
      ],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 2100,
      completedProjects: 18500,
      averageRating: 4.5,
      responseTime: 1,
      successRate: 89,
      monthlyGrowth: 5,
    },
    subcategories: [
      {
        id: 'tadilat-dekorasyon',
        name: 'Tadilat & Dekorasyon',
        description:
          'Boyacı, elektrikçi, tesisatçı ve genel tadilat hizmetleri',
        serviceCount: 120,
        averagePrice: 1200,
        priceRange: { min: 200, max: 5000 },
        popularServices: [
          'Boyacı',
          'Elektrikçi',
          'Tesisatçı',
          'Döşeme',
          'Mutfak Tadilat',
          'Banyo Tadilat',
          'Salon Dekorasyon',
          'Yatak Odası Dekorasyon',
          'Çocuk Odası Dekorasyon',
          'Ofis Dekorasyon',
          'Mağaza Dekorasyon',
          'Restaurant Dekorasyon',
          'Kafe Dekorasyon',
          'Otel Dekorasyon',
          'Villa Dekorasyon',
          'Daire Dekorasyon',
          'Ev Tadilat',
          'Ofis Tadilat',
          'Dükkan Tadilat',
          'Fabrika Tadilat',
          'Apartman Tadilat',
          'Site Tadilat',
          'Asma Tavan',
          'Alçıpan',
          'Parke Döşeme',
          'Laminat Döşeme',
          'Seramik Döşeme',
          'Granit Döşeme',
          'Mermer Döşeme',
          'Vinyl Döşeme',
          'Halı Döşeme',
          'Duvar Kağıdı',
          'Fayans',
          'Mozaik',
          'Doğrama',
          'Pencere Değişimi',
          'Kapı Değişimi',
          'Dolap Yapımı',
          'Mutfak Dolabı',
          'Giyinme Odası',
          'Kütüphane Yapımı',
          'TV Ünitesi',
          'Yatak Başlığı',
          'Gardırop',
          'Vestiyer',
          'Banyo Dolabı',
          'Ayakkabılık',
          'Kitaplık',
          'Çalışma Masası',
          'Bar Tezgahı',
          'Mutfak Tezgahı',
          'Banyo Tezgahı',
          'Lavabo',
          'Klozet',
          'Duş Kabini',
          'Küvet',
          'Jacuzzi',
          'Sauna',
          'Türk Hamamı',
          'Şömine',
          'Barbekü',
          'Pergola',
          'Tente',
          'Markiz',
          'Güneşlik',
          'Balkon Kapatma',
          'Cam Balkon',
          'PVC Doğrama',
          'Alüminyum Doğrama',
          'Ahşap Doğrama',
          'Çelik Doğrama',
          'Anahtar Teslim Tadilat',
          'Proje Hazırlama',
          'İç Mimar',
          'Mimar',
          'İnşaat Mühendisi',
          'Yapı Denetim',
          'İnşaat Ruhsatı',
          'Yapı Kullanma İzni',
          'Emlak Ekspertizi',
          'Hasar Tespit',
          'Keşif Çıkarma',
          'Metraj Hesaplama',
          'Maliyet Analizi',
          'İş Planı',
          'Zaman Çizelgesi',
          'Malzeme Temini',
          'İş Güvenliği',
          'Temizlik',
          'Moloz Temizliği',
          'İnşaat Temizliği',
          'Tadilat Sonrası Temizlik',
          'Boyama Öncesi Hazırlık',
          'Duvar Tamiri',
          'Çatlak Tamiri',
          'Nem Sorunu',
          'İzolasyon',
          'Isı İzolasyonu',
          'Su İzolasyonu',
          'Ses İzolasyonu',
          'Yangın İzolasyonu',
          'Çatı Tamiri',
          'Çatı İzolasyonu',
          'Teras İzolasyonu',
          'Balkon İzolasyonu',
          'Bodrum İzolasyonu',
          'Zemin İzolasyonu',
          'Duvar İzolasyonu',
          'Tavan İzolasyonu',
          'Kış Bahçesi',
          'Cam Tavan',
          'Cam Duvar',
          'Akıllı Ev Sistemleri',
          'Otomasyon',
          'Aydınlatma Sistemleri',
          'LED Aydınlatma',
          'Dekoratif Aydınlatma',
          'Bahçe Aydınlatması',
          'Dış Mekan Aydınlatması',
          'Güvenlik Aydınlatması',
          'Acil Aydınlatma',
        ],
        slug: 'tadilat-dekorasyon',
        parentCategoryId: 'ev-yasam',
      },
      {
        id: 'temizlik',
        name: 'Temizlik Hizmetleri',
        description: 'Ev, ofis ve genel temizlik hizmetleri',
        serviceCount: 80,
        averagePrice: 400,
        priceRange: { min: 100, max: 1500 },
        popularServices: [
          'Ev Temizliği',
          'Ofis Temizliği',
          'Derin Temizlik',
          'Cam Silme',
          'Halı Yıkama',
          'Koltuk Yıkama',
          'Perdé Yıkama',
          'Battaniye Yıkama',
          'Yatak Yıkama',
          'Mobilya Temizliği',
          'Mutfak Temizliği',
          'Banyo Temizliği',
          'Balkon Temizliği',
          'Teras Temizliği',
          'Bahçe Temizliği',
          'Garaj Temizliği',
          'Bodrum Temizliği',
          'Çatı Temizliği',
          'Merdiven Temizliği',
          'Apartman Temizliği',
          'Site Temizliği',
          'Villa Temizliği',
          'Yat Temizliği',
          'Tekne Temizliği',
          'Karavan Temizliği',
          'Araç İç Temizlik',
          'Detaylı Araç Temizliği',
          'Motor Temizliği',
          'Jant Temizliği',
          'Koltuk Deri Bakımı',
          'Torpido Bakımı',
          'İnşaat Sonrası Temizlik',
          'Tadilat Sonrası Temizlik',
          'Taşınma Sonrası Temizlik',
          'Taşınma Öncesi Temizlik',
          'Kiralık Ev Temizliği',
          'Satılık Ev Temizliği',
          'Etkinlik Sonrası Temizlik',
          'Düğün Sonrası Temizlik',
          'Parti Sonrası Temizlik',
          'Mağaza Temizliği',
          'Restaurant Temizliği',
          'Kafe Temizliği',
          'Otel Temizliği',
          'Hastane Temizliği',
          'Okul Temizliği',
          'Fabrika Temizliği',
          'Depo Temizliği',
          'Atölye Temizliği',
          'Showroom Temizliği',
          'Galeri Temizliği',
          'Müze Temizliği',
          'Tiyatro Temizliği',
          'Sinema Temizliği',
          'Spor Salonu Temizliği',
          'Havuz Temizliği',
          'Havuz Kimyasal Bakımı',
          'Jakuzi Temizliği',
          'Sauna Temizliği',
          'Hamam Temizliği',
          'Cam Giydirme Temizliği',
          'Dış Cephe Temizliği',
          'Yüksekten Cam Silme',
          'Ağaç Budama Sonrası Temizlik',
          'Kış Sonrası Bahçe Temizliği',
          'İlaçlama',
          'Dezenfeksiyon',
          'Haşere İlaçlama',
          'Hamam Böceği İlaçlaması',
          'Pire İlaçlama',
          'Kene İlaçlama',
          'Sivrisinek İlaçlama',
          'Fare İlaçlama',
          'Karınca İlaçlama',
          'Arı Kovanı Kaldırma',
          'Yılan Yakalama',
          'Güvercin Kovucu',
          'Koku Giderme',
          'Sigara Kokusu Giderme',
          'Nem Kokusu Giderme',
        ],
        slug: 'temizlik',
        parentCategoryId: 'ev-yasam',
      },
      {
        id: 'nakliye-tasima',
        name: 'Nakliye & Taşıma',
        description: 'Evden eve nakliye, ofis taşıma ve kurye hizmetleri',
        serviceCount: 40,
        averagePrice: 800,
        priceRange: { min: 150, max: 3000 },
        popularServices: [
          'Evden Eve Nakliye',
          'Ofis Taşıma',
          'Kurye',
          'Şehir İçi Nakliye',
          'Şehirler Arası Nakliye',
          'Uluslararası Nakliye',
          'Parça Eşya Taşıma',
          'Asansörlü Nakliye',
          'Ambar Depolama',
          'Eşya Paketleme',
          'Mobilya Demontaj',
          'Mobilya Montaj',
          'Piyano Taşıma',
          'Kasa Taşıma',
          'Çamaşır Makinesi Taşıma',
          'Buzdolabı Taşıma',
          'Bulaşık Makinesi Taşıma',
          'Beyaz Eşya Taşıma',
          'Elektronik Eşya Taşıma',
          'Antika Eşya Taşıma',
          'Tablo Taşıma',
          'Müzik Enstrümanı Taşıma',
          'Motosiklet Taşıma',
          'Bisiklet Taşıma',
          'Araç Taşıma',
          'Tekne Taşıma',
          'Karavan Taşıma',
          'Ağır Yük Taşıma',
          'İnşaat Malzemesi Taşıma',
          'Hafriyat Taşıma',
          'Moloz Taşıma',
          'Hurda Taşıma',
          'Mobilya Taşıma',
          'Koltuk Taşıma',
          'Yatak Taşıma',
          'Gardırop Taşıma',
          'Masa Taşıma',
          'Sandalye Taşıma',
          'Dolap Taşıma',
          'Kitaplık Taşıma',
        ],
        slug: 'nakliye-tasima',
        parentCategoryId: 'ev-yasam',
      },
      {
        id: 'bahce-peyzaj',
        name: 'Bahçe & Peyzaj',
        description: 'Bahçe düzenleme, peyzaj tasarımı ve bitki bakımı',
        serviceCount: 25,
        averagePrice: 900,
        priceRange: { min: 200, max: 4000 },
        popularServices: [
          'Peyzaj Tasarımı',
          'Bahçe Bakımı',
          'Çim Biçme',
          'Ağaç Budama',
          'Çit Budama',
          'Çiçek Dikimi',
          'Ağaç Dikimi',
          'Fide Dikimi',
          'Tohum Ekimi',
          'Toprak Hazırlama',
          'Gübreleme',
          'İlaçlama',
          'Sulama Sistemi',
          'Otomatik Sulama',
          'Damla Sulama',
          'Yağmurlama Sulama',
          'Havuz Yapımı',
          'Süs Havuzu',
          'Şelale Yapımı',
          'Bahçe Aydınlatması',
          'Bahçe Mobilyası',
          'Pergola Yapımı',
          'Çardak Yapımı',
          'Bahçe Yolu',
          'Taş Döşeme',
          'Deck Döşeme',
        ],
        slug: 'bahce-peyzaj',
        parentCategoryId: 'ev-yasam',
      },
      {
        id: 'guvenlik-sistemleri',
        name: 'Güvenlik Sistemleri',
        description: 'Alarm, kamera ve güvenlik sistemi kurulumu',
        serviceCount: 15,
        averagePrice: 1500,
        priceRange: { min: 300, max: 5000 },
        popularServices: [
          'Kamera Sistemi',
          'Alarm Sistemi',
          'Smart Lock',
          'Güvenlik Kamerası',
          'IP Kamera',
          'CCTV Sistemi',
          'Kablosuz Kamera',
          'Gece Görüşlü Kamera',
          'Hareket Sensörlü Kamera',
          'Akıllı Kapı Zili',
          'Video İnterkom',
          'Parmak İzi Sistemi',
          'Yüz Tanıma Sistemi',
          'Kartlı Geçiş Sistemi',
          'Turnike Sistemi',
        ],
        slug: 'guvenlik-sistemleri',
        parentCategoryId: 'ev-yasam',
      },
    ],
  },

  // 5. EĞİTİM & DANIŞMANLIK
  {
    id: 'egitim-danismanlik',
    title: 'Eğitim & Danışmanlık',
    description:
      'Özel ders, yabancı dil, kariyer danışmanlığı ve eğitim hizmetleri',
    shortDescription: 'Özel ders ve kariyer danışmanlığı',
    icon: 'GraduationCap',
    iconColor: '#6366F1', // Indigo-500
    serviceCount: 80,
    averagePrice: 300,
    priceRange: { min: 50, max: 2000 },
    topSkills: [
      'İngilizce',
      'Matematik',
      'Programlama',
      'Müzik',
      'Kariyer Koçluğu',
    ],
    popularServices: [
      'İngilizce Dersi',
      'Matematik Dersi',
      'CV Hazırlama',
      'Kariyer Danışmanlığı',
      'Özel Ders Matematik',
      'Özel Ders Fizik',
      'Özel Ders Kimya',
      'Özel Ders Biyoloji',
      'Özel Ders Türkçe',
      'Özel Ders Tarih',
      'Özel Ders Coğrafya',
      'Özel Ders Felsefe',
      'İngilizce Konuşma',
      'İngilizce Gramer',
      'İngilizce Yazma',
      'İngilizce Okuma',
      'IELTS Hazırlık',
      'TOEFL Hazırlık',
      'YDS Hazırlık',
      'YKS Hazırlık',
      'LGS Hazırlık',
      'Üniversite Hazırlık',
      'Almanca Dersi',
      'Fransızca Dersi',
      'İspanyolca Dersi',
      'İtalyanca Dersi',
      'Rusça Dersi',
      'Çince Dersi',
      'Japonca Dersi',
      'Korece Dersi',
      'Arapça Dersi',
      'Piyano Dersi',
      'Gitar Dersi',
      'Keman Dersi',
      'Flüt Dersi',
      'Davul Dersi',
      'Ses Eğitimi',
      'Müzik Teorisi',
      'Resim Dersi',
      'Karakalem',
      'Yağlı Boya',
      'Suluboya',
      'Pastel',
      'Dijital Resim',
      'Grafik Tasarım Dersi',
      'Fotoğrafçılık Dersi',
      'Video Editing Dersi',
      'Programlama Dersi',
      'Python Dersi',
      'Java Dersi',
      'C++ Dersi',
      'Web Tasarım Dersi',
      'Excel Dersi',
      'Word Dersi',
      'PowerPoint Dersi',
      'Photoshop Dersi',
      'Illustrator Dersi',
      'AutoCAD Dersi',
      'SolidWorks Dersi',
      '3D Max Dersi',
      'SketchUp Dersi',
      'Revit Dersi',
      'MATLAB Dersi',
      'R Programlama',
      'SQL Dersi',
      'İstatistik Dersi',
      'Ekonomi Dersi',
      'Muhasebe Dersi',
      'İşletme Dersi',
      'Pazarlama Dersi',
      'Proje Yönetimi',
      'Liderlik Koçluğu',
      'Motivasyon Koçluğu',
      'Yaşam Koçluğu',
      'İletişim Becerileri',
      'Sunum Teknikleri',
      'Zaman Yönetimi',
      'Stres Yönetimi',
      'Kişisel Gelişim',
      'NLP Koçluğu',
      'Satış Teknikleri',
      'Müzakere Teknikleri',
    ],
    trending: false,
    featured: false,
    order: 5,
    slug: 'egitim-danismanlik',
    metadata: {
      seoTitle: 'Eğitim & Danışmanlık Hizmetleri | MarifetBul',
      seoDescription:
        'Özel ders, yabancı dil öğretimi ve kariyer danışmanlığı hizmetleri.',
      keywords: [
        'özel ders',
        'ingilizce dersi',
        'matematik',
        'kariyer danışmanlığı',
      ],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 650,
      completedProjects: 4200,
      averageRating: 4.9,
      responseTime: 2,
      successRate: 96,
      monthlyGrowth: 7,
    },
    subcategories: [
      {
        id: 'ozel-ders',
        name: 'Özel Ders',
        description:
          'İlkokul, ortaokul, lise ve üniversite özel ders hizmetleri',
        serviceCount: 35,
        averagePrice: 200,
        priceRange: { min: 50, max: 800 },
        popularServices: [
          'Matematik',
          'Fizik',
          'Kimya',
          'Türkçe',
          'Biyoloji',
          'Tarih',
          'Coğrafya',
          'Felsefe',
          'Edebiyat',
          'Geometri',
          'İngilizce',
          'İlkokul Özel Ders',
          'Ortaokul Özel Ders',
          'Lise Özel Ders',
          'Üniversite Özel Ders',
          'YKS Hazırlık',
          'LGS Hazırlık',
          'KPSS Hazırlık',
          'ALES Hazırlık',
          'DGS Hazırlık',
          'YÖKDİL Hazırlık',
          'SAT Hazırlık',
          'GRE Hazırlık',
          'GMAT Hazırlık',
          'Calculus',
          'Linear Algebra',
          'Differential Equations',
          'Probability',
          'Statistics',
          'Ekonomi',
          'İşletme',
          'Muhasebe',
          'Finans',
          'Hukuk',
          'Tıp',
        ],
        slug: 'ozel-ders',
        parentCategoryId: 'egitim-danismanlik',
      },
      {
        id: 'yabanci-dil',
        name: 'Yabancı Dil',
        description: 'İngilizce, Almanca, Fransızca ve diğer dil eğitimleri',
        serviceCount: 25,
        averagePrice: 250,
        priceRange: { min: 80, max: 1000 },
        popularServices: [
          'İngilizce',
          'Almanca',
          'IELTS Hazırlık',
          'TOEFL Hazırlık',
          'YDS Hazırlık',
          'YÖKDİL Hazırlık',
          'Cambridge Sınavları',
          'Business English',
          'Conversation English',
          'Grammar',
          'Writing',
          'Reading',
          'Listening',
          'Speaking',
          'Fransızca',
          'İspanyolca',
          'İtalyanca',
          'Rusça',
          'Çince',
          'Japonca',
          'Korece',
          'Arapça',
          'Portekizce',
          'Yunanca',
          'Latince',
        ],
        slug: 'yabanci-dil',
        parentCategoryId: 'egitim-danismanlik',
      },
      {
        id: 'kariyer-danismanlik',
        name: 'Kariyer Danışmanlığı',
        description: 'CV hazırlama, iş görüşmesi koçluğu ve kariyer planlama',
        serviceCount: 12,
        averagePrice: 800,
        priceRange: { min: 200, max: 2000 },
        popularServices: [
          'CV Hazırlama',
          'LinkedIn Optimizasyonu',
          'İş Görüşmesi Koçluğu',
          'Motivasyon Mektubu',
          'Portfolio Hazırlama',
          'Kariyer Planlama',
          'İş Arama Stratejisi',
          'Kişisel Marka',
          'Networking Koçluğu',
          'Referans Mektubu',
          'Özgeçmiş Düzenleme',
          'Executive CV',
        ],
        slug: 'kariyer-danismanlik',
        trending: true,
        parentCategoryId: 'egitim-danismanlik',
      },
      {
        id: 'sanat-muzik',
        name: 'Sanat & Müzik',
        description: 'Müzik enstrümanları, resim ve sanat eğitimleri',
        serviceCount: 8,
        averagePrice: 350,
        priceRange: { min: 100, max: 1200 },
        popularServices: [
          'Piyano',
          'Gitar',
          'Resim',
          'Dans',
          'Keman',
          'Bağlama',
          'Davul',
          'Flüt',
        ],
        slug: 'sanat-muzik',
        parentCategoryId: 'egitim-danismanlik',
      },
    ],
  },

  // 6. SAĞLIK & KİŞİSEL BAKIM
  {
    id: 'saglik-kisisel-bakim',
    title: 'Sağlık & Kişisel Bakım',
    description: 'Güzellik, fitness, beslenme ve sağlık hizmetleri',
    shortDescription: 'Güzellik, fitness ve sağlık',
    icon: 'Heart',
    iconColor: '#EC4899', // Pink-500
    serviceCount: 50,
    averagePrice: 400,
    priceRange: { min: 80, max: 2000 },
    topSkills: ['Kuaförlük', 'Makyaj', 'Fitness', 'Beslenme', 'Masaj'],
    popularServices: [
      'Kuaförlük',
      'Makyaj',
      'Kişisel Antrenörlük',
      'Beslenme Koçluğu',
    ],
    trending: false,
    featured: false,
    order: 6,
    slug: 'saglik-kisisel-bakim',
    metadata: {
      seoTitle: 'Sağlık & Kişisel Bakım Hizmetleri | MarifetBul',
      seoDescription:
        'Güzellik, fitness, beslenme ve kişisel bakım uzmanları ile randevu alın.',
      keywords: ['kuaförlük', 'makyaj', 'fitness', 'beslenme koçluğu', 'masaj'],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 380,
      completedProjects: 2800,
      averageRating: 4.7,
      responseTime: 1,
      successRate: 92,
      monthlyGrowth: 4,
    },
    subcategories: [
      {
        id: 'guzellik-estetik',
        name: 'Güzellik & Estetik',
        description: 'Kuaförlük, makyaj, nail art ve cilt bakımı',
        serviceCount: 25,
        averagePrice: 350,
        priceRange: { min: 80, max: 1500 },
        popularServices: [
          'Kuaförlük',
          'Makyaj',
          'Nail Art',
          'Cilt Bakımı',
          'Saç Kesimi',
          'Saç Boyama',
          'Balyaj',
          'Ombre',
          'Perma',
          'Fön',
          'Topuz',
          'Örgü Saç',
          'Saç Kaynak',
          'Keratin Bakımı',
          'Botox Saç Bakımı',
          'Manikür',
          'Pedikür',
          'Protez Tırnak',
          'Kalıcı Oje',
          'Tırnak Tasarımı',
          'Kaş Dizaynı',
          'Kaş Laminasyon',
          'Kirpik Lifting',
          'İpek Kirpik',
          'Microblading',
        ],
        slug: 'guzellik-estetik',
        parentCategoryId: 'saglik-kisisel-bakim',
      },
      {
        id: 'fitness-saglik',
        name: 'Fitness & Sağlık',
        description: 'Kişisel antrenörlük, yoga, pilates ve fitness koçluğu',
        serviceCount: 15,
        averagePrice: 500,
        priceRange: { min: 150, max: 2000 },
        popularServices: [
          'Kişisel Antrenörlük',
          'Yoga',
          'Pilates',
          'Beslenme Koçluğu',
          'Zumba',
          'Aerobik',
          'Crossfit',
          'Functional Training',
          'TRX',
          'Spinning',
          'Step',
          'Kickbox',
          'Body Pump',
          'Kilo Verme Programı',
          'Kas Geliştirme',
        ],
        slug: 'fitness-saglik',
        parentCategoryId: 'saglik-kisisel-bakim',
      },
      {
        id: 'wellness-spa',
        name: 'Wellness & SPA',
        description: 'Masaj, aromaterapi ve wellness hizmetleri',
        serviceCount: 10,
        averagePrice: 400,
        priceRange: { min: 100, max: 1200 },
        popularServices: [
          'Masaj',
          'Aromaterapi',
          'Sağlıklı Yaşam Koçluğu',
          'İsveç Masajı',
          'Thai Masajı',
          'Shiatsu',
          'Refleksoloji',
          'Hamam',
          'Sauna',
          'Spa Terapisi',
        ],
        slug: 'wellness-spa',
        parentCategoryId: 'saglik-kisisel-bakim',
      },
    ],
  },

  // 7-16. Diğer Kategoriler (Özet halinde - gerekirse detaylandırılabilir)
  {
    id: 'otomotiv',
    title: 'Otomotiv',
    description: 'Araç bakım, onarım ve otomotiv hizmetleri',
    shortDescription: 'Araç bakım ve onarım',
    icon: 'Car',
    iconColor: '#EF4444', // Red-500
    serviceCount: 30,
    averagePrice: 600,
    priceRange: { min: 100, max: 3000 },
    topSkills: ['Araç Bakım', 'Elektrik', 'Motor', 'Klima', 'Detaylı Temizlik'],
    popularServices: ['Araç Bakımı', 'Elektrik Tamiri', 'Klima Servisi'],
    trending: false,
    featured: false,
    order: 7,
    slug: 'otomotiv',
    metadata: {
      seoTitle: 'Otomotiv Hizmetleri | MarifetBul',
      seoDescription:
        'Araç bakım, onarım ve otomotiv uzmanları ile araç sorunlarınızı çözün.',
      keywords: ['araç bakım', 'araç tamiri', 'otomotiv', 'elektrik tamiri'],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 180,
      completedProjects: 1250,
      averageRating: 4.4,
      responseTime: 2,
      successRate: 88,
      monthlyGrowth: 3,
    },
    subcategories: [
      {
        id: 'arac-bakim-onarim',
        name: 'Araç Bakım & Onarım',
        description: 'Periyodik bakım, mekanik onarım ve motor tamiri',
        serviceCount: 15,
        averagePrice: 800,
        priceRange: { min: 150, max: 2500 },
        popularServices: [
          'Yağ Değişimi',
          'Filtre Değişimi',
          'Fren Tamiri',
          'Balata Değişimi',
          'Disk Değişimi',
          'Amortisör Değişimi',
          'Egzoz Değişimi',
          'Motor Revizyonu',
          'Enjektör Temizliği',
          'Triger Seti Değişimi',
          'Buji Değişimi',
          'Akü Değişimi',
          'Lastik Değişimi',
          'Rot Balans',
          'Süspansiyon Tamiri',
        ],
        slug: 'arac-bakim-onarim',
        parentCategoryId: 'otomotiv',
      },
      {
        id: 'arac-elektrik-elektronik',
        name: 'Araç Elektrik & Elektronik',
        description: 'Elektrik arızaları, klima ve oto elektrik hizmetleri',
        serviceCount: 10,
        averagePrice: 600,
        priceRange: { min: 100, max: 2000 },
        popularServices: [
          'Klima Gazı Dolumu',
          'Klima Servisi',
          'Araç Teşhis',
          'Marş Motoru Tamiri',
          'Alternatör Tamiri',
          'Araç Beyni Tamiri',
          'Elektrik Tesisatı',
          'Far Ayarı',
          'Sis Farı Montajı',
          'Xenon Far Montajı',
        ],
        slug: 'arac-elektrik-elektronik',
        parentCategoryId: 'otomotiv',
      },
      {
        id: 'arac-estetik-temizlik',
        name: 'Araç Estetik & Temizlik',
        description: 'Detaylı araç temizliği, kaplama ve koruma hizmetleri',
        serviceCount: 5,
        averagePrice: 400,
        priceRange: { min: 100, max: 1500 },
        popularServices: [
          'Detaylı İç Temizlik',
          'Motor Yıkama',
          'Seramik Kaplama',
          'Nano Seramik',
          'Araç Cilalama',
        ],
        slug: 'arac-estetik-temizlik',
        parentCategoryId: 'otomotiv',
      },
    ],
  },

  {
    id: 'finans-muhasebe',
    title: 'Finans & Muhasebe',
    description: 'Muhasebe, vergi, yatırım danışmanlığı ve finans hizmetleri',
    shortDescription: 'Muhasebe ve finans danışmanlığı',
    icon: 'DollarSign',
    iconColor: '#EAB308', // Yellow-500
    serviceCount: 25,
    averagePrice: 1200,
    priceRange: { min: 200, max: 5000 },
    topSkills: ['Muhasebe', 'Vergi', 'Yatırım', 'Mali Müşavirlik'],
    popularServices: [
      'Muhasebe Hizmetleri',
      'Vergi Danışmanlığı',
      'Yatırım Koçluğu',
    ],
    trending: false,
    featured: false,
    order: 8,
    slug: 'finans-muhasebe',
    metadata: {
      seoTitle: 'Finans & Muhasebe Hizmetleri | MarifetBul',
      seoDescription:
        'Muhasebe, vergi ve yatırım danışmanlığı için uzman mali müşavirler.',
      keywords: ['muhasebe', 'vergi danışmanlığı', 'mali müşavir', 'yatırım'],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 120,
      completedProjects: 980,
      averageRating: 4.8,
      responseTime: 4,
      successRate: 94,
      monthlyGrowth: 6,
    },
    subcategories: [
      {
        id: 'muhasebe-hizmetleri',
        name: 'Muhasebe Hizmetleri',
        description: 'Ticari defter tutma, mali raporlama ve muhasebe kayıtları',
        serviceCount: 12,
        averagePrice: 1500,
        priceRange: { min: 300, max: 4000 },
        popularServices: [
          'Ticari Defter Tutma',
          'Mali Tablo Hazırlama',
          'Gelir-Gider Takibi',
          'Fatura Kayıt',
          'Bordro Hazırlama',
          'SGK İşlemleri',
          'E-Fatura',
          'E-Defter',
          'E-Arşiv',
          'Stok Takibi',
          'Cari Hesap Takibi',
          'Banka Mutabakatı',
        ],
        slug: 'muhasebe-hizmetleri',
        parentCategoryId: 'finans-muhasebe',
      },
      {
        id: 'vergi-danismanlik',
        name: 'Vergi Danışmanlığı',
        description: 'Vergi beyannamesi, matrah indirim ve vergi optimizasyonu',
        serviceCount: 8,
        averagePrice: 1000,
        priceRange: { min: 200, max: 3000 },
        popularServices: [
          'Vergi Beyannamesi',
          'KDV Beyannamesi',
          'Gelir Vergisi Beyanı',
          'Kurumlar Vergisi',
          'Stopaj Beyanı',
          'Muhtasar Beyanı',
          'Geçici Vergi',
          'Vergi İadesi',
        ],
        slug: 'vergi-danismanlik',
        parentCategoryId: 'finans-muhasebe',
      },
      {
        id: 'yatirim-danismanlik',
        name: 'Yatırım Danışmanlığı',
        description: 'Portföy yönetimi, yatırım stratejisi ve finansal planlama',
        serviceCount: 5,
        averagePrice: 2000,
        priceRange: { min: 500, max: 5000 },
        popularServices: [
          'Portföy Yönetimi',
          'Hisse Senedi Analizi',
          'Kripto Para Danışmanlığı',
          'Emeklilik Planlaması',
          'Finansal Planlama',
        ],
        slug: 'yatirim-danismanlik',
        trending: true,
        parentCategoryId: 'finans-muhasebe',
      },
    ],
  },

  // Diğer kategoriler benzer şekilde devam eder...
  // 9. Çevre & Enerji
  {
    id: 'cevre-enerji',
    title: 'Çevre & Enerji',
    description: 'Güneş enerjisi, çevre danışmanlığı ve sürdürülebilirlik',
    shortDescription: 'Güneş enerji ve çevre çözümleri',
    icon: 'Leaf',
    iconColor: '#22C55E', // Green-500
    serviceCount: 15,
    averagePrice: 2500,
    priceRange: { min: 500, max: 10000 },
    topSkills: ['Güneş Paneli', 'Çevre Danışmanlığı', 'Enerji Verimliliği'],
    popularServices: ['Güneş Paneli Kurulumu', 'Çevre Danışmanlığı'],
    trending: true,
    featured: false,
    order: 9,
    slug: 'cevre-enerji',
    metadata: {
      seoTitle: 'Çevre & Enerji Hizmetleri | MarifetBul',
      seoDescription: 'Güneş enerjisi ve çevre danışmanlığı için uzmanlar.',
      keywords: ['güneş enerjisi', 'çevre danışmanlığı', 'solar panel'],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 60,
      completedProjects: 320,
      averageRating: 4.6,
      responseTime: 3,
      successRate: 91,
      monthlyGrowth: 18,
    },
    subcategories: [
      {
        id: 'gunes-enerjisi',
        name: 'Güneş Enerjisi',
        description: 'Solar panel kurulumu ve güneş enerjisi sistemleri',
        serviceCount: 8,
        averagePrice: 3500,
        priceRange: { min: 1000, max: 10000 },
        popularServices: [
          'Güneş Paneli Kurulumu',
          'Solar Enerji Sistemi',
          'Güneş Kollektörü',
          'İnverter Kurulumu',
          'Batarya Sistemi',
          'Hibrit Sistem',
          'Off-Grid Sistem',
          'On-Grid Sistem',
        ],
        slug: 'gunes-enerjisi',
        trending: true,
        parentCategoryId: 'cevre-enerji',
      },
      {
        id: 'cevre-danismanlik',
        name: 'Çevre Danışmanlığı',
        description: 'Çevre yönetimi, sürdürülebilirlik ve çevre mühendisliği',
        serviceCount: 7,
        averagePrice: 2000,
        priceRange: { min: 500, max: 5000 },
        popularServices: [
          'Çevre Yönetim Sistemi',
          'Atık Yönetimi',
          'Su Yönetimi',
          'Enerji Verimliliği',
          'Karbon Ayak İzi',
          'Sürdürülebilirlik Danışmanlığı',
          'Çevre İzin Belgesi',
        ],
        slug: 'cevre-danismanlik',
        parentCategoryId: 'cevre-enerji',
      },
    ],
  },

  // 10. Gıda & İçecek
  {
    id: 'gida-icecek',
    title: 'Gıda & İçecek',
    description: 'Catering, yemek hizmetleri ve mutfak danışmanlığı',
    shortDescription: 'Catering ve yemek hizmetleri',
    icon: 'ChefHat',
    iconColor: '#F97316', // Orange-500
    serviceCount: 20,
    averagePrice: 800,
    priceRange: { min: 150, max: 4000 },
    topSkills: ['Catering', 'Yemek Hazırlama', 'Pastane', 'Barista'],
    popularServices: ['Etkinlik Catering', 'Ev Aşçısı', 'Pasta Yapımı'],
    trending: false,
    featured: false,
    order: 10,
    slug: 'gida-icecek',
    metadata: {
      seoTitle: 'Gıda & İçecek Hizmetleri | MarifetBul',
      seoDescription: 'Catering, özel yemek hazırlama ve mutfak hizmetleri.',
      keywords: ['catering', 'yemek hazırlama', 'pasta yapımı', 'chef'],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 90,
      completedProjects: 650,
      averageRating: 4.5,
      responseTime: 2,
      successRate: 87,
      monthlyGrowth: 4,
    },
    subcategories: [
      {
        id: 'catering-hizmetleri',
        name: 'Catering Hizmetleri',
        description: 'Etkinlik catering, toplu yemek ve özel günler için yemek hizmeti',
        serviceCount: 12,
        averagePrice: 1200,
        priceRange: { min: 300, max: 4000 },
        popularServices: [
          'Düğün Catering',
          'Etkinlik Catering',
          'Kokteyl İkramı',
          'Açılış Organizasyonu',
          'Kurumsal Etkinlik Catering',
          'Kahvaltı Catering',
          'Öğle Yemeği Catering',
          'Akşam Yemeği Catering',
          'Kokteyl Catering',
          'Finger Food',
          'Açık Büfe',
          'Oturmalı Yemek',
        ],
        slug: 'catering-hizmetleri',
        parentCategoryId: 'gida-icecek',
      },
      {
        id: 'ev-asci-yemek',
        name: 'Ev Aşçısı & Yemek',
        description: 'Özel yemek hazırlama, ev aşçısı ve mutfak hizmetleri',
        serviceCount: 5,
        averagePrice: 600,
        priceRange: { min: 150, max: 2000 },
        popularServices: [
          'Ev Aşçısı',
          'Özel Yemek Hazırlama',
          'Diyet Yemekleri',
          'Vegan Yemekler',
          'Organik Yemekler',
        ],
        slug: 'ev-asci-yemek',
        parentCategoryId: 'gida-icecek',
      },
      {
        id: 'pasta-tatli',
        name: 'Pasta & Tatlı',
        description: 'Özel pasta, kurabiye ve tatlı yapımı',
        serviceCount: 3,
        averagePrice: 400,
        priceRange: { min: 100, max: 1500 },
        popularServices: [
          'Doğum Günü Pastası',
          'Düğün Pastası',
          'Cupcake',
        ],
        slug: 'pasta-tatli',
        parentCategoryId: 'gida-icecek',
      },
    ],
  },

  // 11. ETKİNLİK & EĞLENCE
  {
    id: 'etkinlik-eglence',
    title: 'Etkinlik & Eğlence',
    description:
      'Düğün organizasyonu, etkinlik planlaması, müzik ve eğlence hizmetleri',
    shortDescription: 'Etkinlik organizasyonu ve eğlence',
    icon: 'PartyPopper',
    iconColor: '#F59E0B', // Amber-500
    serviceCount: 65,
    averagePrice: 2200,
    priceRange: { min: 500, max: 8000 },
    topSkills: [
      'Etkinlik Planlama',
      'DJ',
      'Fotoğrafçılık',
      'Catering',
      'Dekorasyon',
    ],
    popularServices: [
      'Düğün Organizasyonu',
      'DJ Hizmeti',
      'Etkinlik Fotoğrafçılığı',
      'Catering',
    ],
    trending: false,
    featured: true,
    order: 11,
    slug: 'etkinlik-eglence',
    metadata: {
      seoTitle: 'Etkinlik & Eğlence Hizmetleri | MarifetBul',
      seoDescription:
        'Düğün organizasyonu, doğum günü partisi ve etkinlik planlaması hizmetleri.',
      keywords: ['etkinlik organizasyonu', 'düğün', 'parti', 'DJ', 'müzik'],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 320,
      completedProjects: 2100,
      averageRating: 4.7,
      responseTime: 1,
      successRate: 94,
      monthlyGrowth: 6,
    },
    subcategories: [
      {
        id: 'dugun-organizasyon',
        name: 'Düğün Organizasyonu',
        description: 'Düğün planlama, koordinasyon ve dekorasyon hizmetleri',
        serviceCount: 25,
        averagePrice: 3500,
        priceRange: { min: 1000, max: 8000 },
        popularServices: [
          'Düğün Planlama',
          'Nişan Organizasyonu',
          'Kına Gecesi',
          'Düğün Koordinatörlüğü',
          'Düğün Dekorasyonu',
          'Masa Düzeni',
          'Çiçek Süsleme',
          'Balon Süsleme',
          'Işık Sistemi',
          'Ses Sistemi',
          'Sahne Düzeni',
          'Giriş Takı',
          'Masa Takı',
          'Davetiye Tasarımı',
          'Menü Tasarımı',
          'Oturum Planı',
          'Düğün Pastası',
          'Candy Bar',
          'Photo Booth',
          'Fotoğrafçılık',
          'Kameraman',
          'Drone Çekimi',
          'Düğün Videosu',
          'Düğün Albümü',
          'DJ Hizmeti',
        ],
        slug: 'dugun-organizasyon',
        trending: true,
        parentCategoryId: 'etkinlik-eglence',
      },
      {
        id: 'dogum-gunu-parti',
        name: 'Doğum Günü & Parti',
        description: 'Çocuk ve yetişkin parti organizasyonu',
        serviceCount: 20,
        averagePrice: 1500,
        priceRange: { min: 300, max: 4000 },
        popularServices: [
          'Çocuk Doğum Günü',
          'Yetişkin Partisi',
          'Sürpriz Parti',
          'Tema Parti',
          'Animatör',
          'Palyaço',
          'Sihirbaz',
          'Face Painting',
          'Balon Süsleme',
          'Parti Malzemeleri',
          'Pasta',
          'Catering',
          'DJ',
          'Müzik Grubu',
          'Photo Booth',
          'Video Çekimi',
          'Fotoğrafçı',
          'Mekan Kiralama',
          'Bahçe Partisi',
          'Havuz Partisi',
        ],
        slug: 'dogum-gunu-parti',
        parentCategoryId: 'etkinlik-eglence',
      },
      {
        id: 'muzik-eglence',
        name: 'Müzik & Eğlence',
        description: 'DJ, canlı müzik ve eğlence hizmetleri',
        serviceCount: 20,
        averagePrice: 2000,
        priceRange: { min: 500, max: 5000 },
        popularServices: [
          'DJ Hizmeti',
          'Canlı Müzik',
          'Düğün Orkestrası',
          'Solo Sanatçı',
          'İkili Grup',
          'Trio',
          'Kuartet',
          'Caz Grubu',
          'Rock Grubu',
          'Pop Grubu',
          'Türkü Grubu',
          'Fasıl Grubu',
          'Kemancı',
          'Gitarist',
          'Piyanist',
          'Saksafoncu',
          'Davulcu',
          'MC',
          'Sunucu',
          'Moderatör',
        ],
        slug: 'muzik-eglence',
        parentCategoryId: 'etkinlik-eglence',
      },
    ],
  },

  // 12. SPOR & REKREASİYON
  {
    id: 'spor-rekreasyon',
    title: 'Spor & Rekreasyon',
    description:
      'Kişisel antrenörlük, spor koçluğu ve outdoor aktivite hizmetleri',
    shortDescription: 'Spor antrenörlüğü ve rekreasyon',
    icon: 'Dumbbell',
    iconColor: '#10B981', // Emerald-500
    serviceCount: 45,
    averagePrice: 800,
    priceRange: { min: 200, max: 3000 },
    topSkills: ['Kişisel Antrenörlük', 'Yoga', 'Futbol', 'Tenis', 'Yüzme'],
    popularServices: [
      'Kişisel Antrenör',
      'Yoga Dersi',
      'Futbol Antrenörlüğü',
      'Yüzme Dersi',
    ],
    trending: true,
    featured: false,
    order: 12,
    slug: 'spor-rekreasyon',
    metadata: {
      seoTitle: 'Spor & Rekreasyon Hizmetleri | MarifetBul',
      seoDescription:
        'Kişisel antrenör, yoga eğitmeni ve spor koçluğu hizmetleri.',
      keywords: ['personal trainer', 'yoga', 'spor', 'antrenör', 'fitness'],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 180,
      completedProjects: 1350,
      averageRating: 4.8,
      responseTime: 1,
      successRate: 96,
      monthlyGrowth: 8,
    },
    subcategories: [
      {
        id: 'kisisel-antrenorlik',
        name: 'Kişisel Antrenörlük',
        description: 'One-on-one fitness koçluğu ve kişiye özel program',
        serviceCount: 20,
        averagePrice: 1000,
        priceRange: { min: 300, max: 3000 },
        popularServices: [
          'Kişisel Antrenör',
          'Kilo Verme Programı',
          'Kas Geliştirme',
          'Vücut Geliştirme',
          'Functional Training',
          'HIIT',
          'Crossfit',
          'TRX',
          'Pilates',
          'Yoga',
          'Zumba',
          'Aerobik',
          'Step',
          'Spinning',
          'Kickbox',
          'Boks',
          'Muay Thai',
          'Karate',
          'Taekwondo',
          'Judo',
        ],
        slug: 'kisisel-antrenorlik',
        trending: true,
        parentCategoryId: 'spor-rekreasyon',
      },
      {
        id: 'takim-sporlari',
        name: 'Takım Sporları',
        description: 'Futbol, basketbol, voleybol antrenörlüğü',
        serviceCount: 15,
        averagePrice: 600,
        priceRange: { min: 200, max: 2000 },
        popularServices: [
          'Futbol Antrenörlüğü',
          'Basketbol Antrenörlüğü',
          'Voleybol Antrenörlüğü',
          'Hentbol Antrenörlüğü',
          'Masa Tenisi',
          'Badminton',
          'Tenis',
          'Squash',
          'Yüzme',
          'Su Topu',
          'Ragbi',
          'Amerikan Futbolu',
          'Beyzbol',
          'Kriket',
          'Hokey',
        ],
        slug: 'takim-sporlari',
        parentCategoryId: 'spor-rekreasyon',
      },
      {
        id: 'outdoor-aktiviteler',
        name: 'Outdoor Aktiviteler',
        description: 'Dağcılık, kamp, doğa sporları rehberliği',
        serviceCount: 10,
        averagePrice: 800,
        priceRange: { min: 200, max: 2500 },
        popularServices: [
          'Trekking',
          'Dağcılık',
          'Kaya Tırmanışı',
          'Kamp Rehberliği',
          'Doğa Yürüyüşü',
          'Bisiklet Turu',
          'Rafting',
          'Kano',
          'Kayak',
          'Snowboard',
        ],
        slug: 'outdoor-aktiviteler',
        parentCategoryId: 'spor-rekreasyon',
      },
    ],
  },

  // 13. ÇOCUK & BEBEK
  {
    id: 'cocuk-bebek',
    title: 'Çocuk & Bebek',
    description: 'Bebek bakımı, çocuk bakımı, eğitim ve gelişim hizmetleri',
    shortDescription: 'Çocuk bakımı ve eğitimi',
    icon: 'Baby',
    iconColor: '#EC4899', // Pink-500
    serviceCount: 40,
    averagePrice: 600,
    priceRange: { min: 150, max: 2000 },
    topSkills: [
      'Çocuk Bakımı',
      'Eğitim',
      'Psikoloji',
      'İlk Yardım',
      'Beslenme',
    ],
    popularServices: [
      'Bebek Bakıcısı',
      'Çocuk Bakıcısı',
      'Özel Ders',
      'Çocuk Psikolojisi',
    ],
    trending: false,
    featured: true,
    order: 13,
    slug: 'cocuk-bebek',
    metadata: {
      seoTitle: 'Çocuk & Bebek Bakım Hizmetleri | MarifetBul',
      seoDescription:
        'Güvenilir bebek bakıcısı, çocuk bakıcısı ve çocuk eğitimi hizmetleri.',
      keywords: [
        'bebek bakıcısı',
        'çocuk bakıcısı',
        'childcare',
        'çocuk eğitimi',
        'nanny',
      ],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 250,
      completedProjects: 1800,
      averageRating: 4.9,
      responseTime: 1,
      successRate: 98,
      monthlyGrowth: 5,
    },
    subcategories: [
      {
        id: 'bebek-bakim',
        name: 'Bebek Bakımı',
        description: 'Yenidoğan ve bebek bakım hizmetleri',
        serviceCount: 15,
        averagePrice: 700,
        priceRange: { min: 200, max: 2000 },
        popularServices: [
          'Bebek Bakıcısı',
          'Gece Bakımı',
          'Part-time Bakıcı',
          'Full-time Bakıcı',
          'Yenidoğan Bakımı',
          'İkiz Bakımı',
          'Bebek Masajı',
          'Emzirme Danışmanlığı',
          'Uyku Eğitimi',
          'Mama Hazırlama',
          'Hijyen Bakımı',
          'İlk Yardım',
          'Sağlık Takibi',
          'Gelişim Takibi',
          'Oyun Etkinlikleri',
        ],
        slug: 'bebek-bakim',
        parentCategoryId: 'cocuk-bebek',
      },
      {
        id: 'cocuk-bakim',
        name: 'Çocuk Bakımı',
        description: 'Okul öncesi ve okul çağı çocuk bakımı',
        serviceCount: 15,
        averagePrice: 600,
        priceRange: { min: 150, max: 1500 },
        popularServices: [
          'Çocuk Bakıcısı',
          'Okul Servis Eşliği',
          'Ev Ödevi Yardımı',
          'Oyun Arkadaşlığı',
          'Aktivite Planlama',
          'Yemek Hazırlama',
          'Hijyen Bakımı',
          'Giyinme Yardımı',
          'Uyku Düzeni',
          'Davranış Yönetimi',
          'Sosyalleşme',
          'Dil Gelişimi',
          'Motor Gelişim',
          'Bilişsel Gelişim',
          'Duygusal Gelişim',
        ],
        slug: 'cocuk-bakim',
        parentCategoryId: 'cocuk-bebek',
      },
      {
        id: 'cocuk-egitim',
        name: 'Çocuk Eğitimi',
        description: 'Gelişim eğitimi, özel ders ve psikolojik destek',
        serviceCount: 10,
        averagePrice: 500,
        priceRange: { min: 150, max: 1500 },
        popularServices: [
          'Erken Çocukluk Eğitimi',
          'Okuma Yazma Öğretimi',
          'Matematik Dersi',
          'İngilizce Dersi',
          'Müzik Dersi',
          'Resim Dersi',
          'Spor Aktiviteleri',
          'Çocuk Psikolojisi',
          'Gelişim Danışmanlığı',
          'Dikkat Eğitimi',
        ],
        slug: 'cocuk-egitim',
        parentCategoryId: 'cocuk-bebek',
      },
    ],
  },

  // 14. YAŞLI BAKIM
  {
    id: 'yasli-bakim',
    title: 'Yaşlı Bakımı',
    description: 'Yaşlı bakımı, hasta bakımı ve evde sağlık hizmetleri',
    shortDescription: 'Yaşlı ve hasta bakımı',
    icon: 'Heart',
    iconColor: '#DC2626', // Red-600
    serviceCount: 25,
    averagePrice: 900,
    priceRange: { min: 300, max: 2500 },
    topSkills: [
      'Yaşlı Bakımı',
      'Tıbbi Bakım',
      'Refakatçilik',
      'İlk Yardım',
      'Hemşirelik',
    ],
    popularServices: [
      'Yaşlı Bakımı',
      'Hasta Bakımı',
      'Evde Hemşirelik',
      'Refakatçi',
    ],
    trending: false,
    featured: false,
    order: 14,
    slug: 'yasli-bakim',
    metadata: {
      seoTitle: 'Yaşlı Bakımı Hizmetleri | MarifetBul',
      seoDescription:
        'Profesyonel yaşlı bakımı, hasta bakımı ve evde sağlık hizmetleri.',
      keywords: [
        'yaşlı bakımı',
        'hasta bakımı',
        'evde bakım',
        'hemşire',
        'refakatçi',
      ],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 120,
      completedProjects: 890,
      averageRating: 4.8,
      responseTime: 1,
      successRate: 97,
      monthlyGrowth: 3,
    },
    subcategories: [
      {
        id: 'yasli-bakim-hizmeti',
        name: 'Yaşlı Bakım Hizmeti',
        description: 'Evde yaşlı bakımı ve günlük yaşam desteği',
        serviceCount: 15,
        averagePrice: 1000,
        priceRange: { min: 400, max: 2500 },
        popularServices: [
          'Yaşlı Bakımı',
          'Yatılı Bakım',
          'Gündüzlü Bakım',
          'Gece Bakımı',
          'Part-time Bakım',
          'Full-time Bakım',
          'Hijyen Bakımı',
          'Yemek Hazırlama',
          'İlaç Takibi',
          'Ölçüm Takibi',
          'Doktor Randevusu',
          'Egzersiz Yardımı',
          'Yürüyüş Eşliği',
          'Sohbet Arkadaşlığı',
          'Ev İşleri Yardımı',
        ],
        slug: 'yasli-bakim-hizmeti',
        parentCategoryId: 'yasli-bakim',
      },
      {
        id: 'hasta-bakim',
        name: 'Hasta Bakımı',
        description: 'Evde hasta bakımı ve tıbbi destek hizmetleri',
        serviceCount: 7,
        averagePrice: 1200,
        priceRange: { min: 500, max: 2500 },
        popularServices: [
          'Hasta Bakımı',
          'Yatalak Hasta Bakımı',
          'Alzheimer Bakımı',
          'Parkinson Bakımı',
          'Kanser Hastası Bakımı',
          'Felçli Hasta Bakımı',
          'Diyabet Hastası Bakımı',
        ],
        slug: 'hasta-bakim',
        parentCategoryId: 'yasli-bakim',
      },
      {
        id: 'evde-saglik',
        name: 'Evde Sağlık',
        description: 'Hemşirelik, fizyoterapi ve evde sağlık hizmetleri',
        serviceCount: 3,
        averagePrice: 800,
        priceRange: { min: 300, max: 2000 },
        popularServices: [
          'Evde Hemşirelik',
          'Fizyoterapi',
          'Refakatçi',
        ],
        slug: 'evde-saglik',
        parentCategoryId: 'yasli-bakim',
      },
    ],
  },

  // 15. HUKUK & KAMU
  {
    id: 'hukuk-kamu',
    title: 'Hukuk & Kamu',
    description: 'Hukuki danışmanlık, resmi işlemler ve kamu hizmetleri',
    shortDescription: 'Hukuki danışmanlık ve resmi işlemler',
    icon: 'Scale',
    iconColor: '#374151', // Gray-700
    serviceCount: 35,
    averagePrice: 1500,
    priceRange: { min: 500, max: 5000 },
    topSkills: [
      'Hukuki Danışmanlık',
      'Belge Hazırlama',
      'Çeviri',
      'Noterlik',
      'Göçmenlik',
    ],
    popularServices: [
      'Hukuki Danışmanlık',
      'Sözleşme Hazırlama',
      'Resmi Çeviri',
      'Vize İşlemleri',
    ],
    trending: false,
    featured: false,
    order: 15,
    slug: 'hukuk-kamu',
    metadata: {
      seoTitle: 'Hukuk & Kamu Hizmetleri | MarifetBul',
      seoDescription: 'Hukuki danışmanlık, resmi işlemler ve kamu hizmetleri.',
      keywords: [
        'hukuki danışmanlık',
        'avukat',
        'resmi işlemler',
        'çeviri',
        'vize',
      ],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 95,
      completedProjects: 720,
      averageRating: 4.6,
      responseTime: 2,
      successRate: 93,
      monthlyGrowth: 2,
    },
    subcategories: [
      {
        id: 'hukuki-danismanlik',
        name: 'Hukuki Danışmanlık',
        description: 'Avukatlık, hukuk danışmanlığı ve yasal destek',
        serviceCount: 18,
        averagePrice: 1800,
        priceRange: { min: 500, max: 5000 },
        popularServices: [
          'Avukatlık',
          'Boşanma Davası',
          'Tazminat Davası',
          'Miras Davası',
          'İcra Takibi',
          'İş Hukuku',
          'Kira Hukuku',
          'Ticaret Hukuku',
          'Ceza Hukuku',
          'Aile Hukuku',
          'Gayrimenkul Hukuku',
          'Fikri Mülkiyet',
          'Sözleşme Hukuku',
          'Şirketler Hukuku',
          'İdare Hukuku',
          'Vergi Hukuku',
          'Medeni Hukuk',
          'Borçlar Hukuku',
        ],
        slug: 'hukuki-danismanlik',
        parentCategoryId: 'hukuk-kamu',
      },
      {
        id: 'resmi-islemler',
        name: 'Resmi İşlemler',
        description: 'Noter, tercüme, vize ve resmi belge işlemleri',
        serviceCount: 12,
        averagePrice: 800,
        priceRange: { min: 200, max: 2000 },
        popularServices: [
          'Noter İşlemleri',
          'Apostil',
          'Tercüme',
          'Yeminli Tercüme',
          'Vize İşlemleri',
          'Pasaport İşlemleri',
          'İkamet İzni',
          'Çalışma İzni',
          'Nüfus İşlemleri',
          'Tapu İşlemleri',
          'Araç İşlemleri',
          'SGK İşlemleri',
        ],
        slug: 'resmi-islemler',
        parentCategoryId: 'hukuk-kamu',
      },
      {
        id: 'gocmenlik-vize',
        name: 'Göçmenlik & Vize',
        description: 'Vize danışmanlığı, göç işlemleri ve vatandaşlık',
        serviceCount: 5,
        averagePrice: 2000,
        priceRange: { min: 800, max: 5000 },
        popularServices: [
          'Vize Danışmanlığı',
          'Göç Danışmanlığı',
          'Oturma İzni',
          'Vatandaşlık Başvurusu',
          'İltica Başvurusu',
        ],
        slug: 'gocmenlik-vize',
        parentCategoryId: 'hukuk-kamu',
      },
    ],
  },

  // 16. TURİZM & SEYAHAT
  {
    id: 'turizm-seyahat',
    title: 'Turizm & Seyahat',
    description: 'Seyahat planlaması, rehberlik ve turizm hizmetleri',
    shortDescription: 'Seyahat planlaması ve rehberlik',
    icon: 'MapPin',
    iconColor: '#0EA5E9', // Sky-500
    serviceCount: 30,
    averagePrice: 1200,
    priceRange: { min: 300, max: 4000 },
    topSkills: [
      'Seyahat Planlaması',
      'Rehberlik',
      'Otel Rezervasyonu',
      'Çeviri',
      'Fotoğrafçılık',
    ],
    popularServices: [
      'Seyahat Planlaması',
      'Rehberlik',
      'Otel Rezervasyonu',
      'Tur Organizasyonu',
    ],
    trending: true,
    featured: false,
    order: 16,
    slug: 'turizm-seyahat',
    metadata: {
      seoTitle: 'Turizm & Seyahat Hizmetleri | MarifetBul',
      seoDescription:
        'Seyahat planlaması, rehberlik ve tur organizasyonu hizmetleri.',
      keywords: ['seyahat planlaması', 'rehber', 'tur', 'turizm', 'seyahat'],
      lastUpdated: '2025-10-04',
      isActive: true,
    },
    stats: {
      totalFreelancers: 85,
      completedProjects: 540,
      averageRating: 4.7,
      responseTime: 1,
      successRate: 95,
      monthlyGrowth: 7,
    },
    subcategories: [
      {
        id: 'seyahat-planlama',
        name: 'Seyahat Planlama',
        description: 'Tatil planlama, rota oluşturma ve seyahat danışmanlığı',
        serviceCount: 15,
        averagePrice: 1500,
        priceRange: { min: 400, max: 4000 },
        popularServices: [
          'Tatil Planlama',
          'Rota Planlama',
          'Otobüs Bileti',
          'Uçak Bileti',
          'Otel Rezervasyonu',
          'Transfer Hizmeti',
          'Araç Kiralama',
          'Tur Planı',
          'Gezi Programı',
          'Balayı Paketi',
          'Aile Tatili',
          'Yurt Dışı Turu',
          'Yurt İçi Turu',
          'Kültür Turu',
          'Macera Turu',
        ],
        slug: 'seyahat-planlama',
        trending: true,
        parentCategoryId: 'turizm-seyahat',
      },
      {
        id: 'rehberlik',
        name: 'Rehberlik Hizmetleri',
        description: 'Turist rehberliği, şehir turu ve özel geziler',
        serviceCount: 10,
        averagePrice: 800,
        priceRange: { min: 200, max: 2000 },
        popularServices: [
          'Turist Rehberi',
          'Şehir Turu',
          'Müze Turu',
          'Tarihi Yerler Turu',
          'Doğa Turu',
          'Fotoğraf Turu',
          'Gastronomi Turu',
          'Alışveriş Turu',
          'Gece Turu',
          'Tekne Turu',
        ],
        slug: 'rehberlik',
        parentCategoryId: 'turizm-seyahat',
      },
      {
        id: 'konaklama-organizasyon',
        name: 'Konaklama & Organizasyon',
        description: 'Otel, pansiyon ve konaklama organizasyonu',
        serviceCount: 5,
        averagePrice: 1000,
        priceRange: { min: 300, max: 3000 },
        popularServices: [
          'Otel Rezervasyonu',
          'Apart Otel',
          'Villa Kiralama',
          'Pansiyon',
          'Hostel',
        ],
        slug: 'konaklama-organizasyon',
        parentCategoryId: 'turizm-seyahat',
      },
    ],
  },
];

// Platform İstatistikleri
export const PLATFORM_STATS = {
  totalCategories: 16,
  totalSubcategories: 89,
  totalFreelancers: 12540,
  totalProjects: 89650,
  averageProjectValue: 1850,
  successRate: 94,
  monthlyGrowth: 8.5,
  activeUsers: 145000,
};

// Trend Kategoriler
export const TRENDING_CATEGORIES = MARKETPLACE_CATEGORIES.filter(
  (cat) => cat.trending
);

// Featured Kategoriler
export const FEATURED_CATEGORIES = MARKETPLACE_CATEGORIES.filter(
  (cat) => cat.featured
);

// Kategori ID'sine göre kategori bulma
export const getCategoryById = (id: string): Category | undefined => {
  return MARKETPLACE_CATEGORIES.find((cat) => cat.id === id);
};

// Popüler kategoriler (hizmet sayısına göre)
export const getPopularCategories = (): Category[] => {
  return [...MARKETPLACE_CATEGORIES].sort(
    (a, b) => b.serviceCount - a.serviceCount
  );
};

// Alfabetik sıralama
export const getCategoriesAlphabetical = (): Category[] => {
  return [...MARKETPLACE_CATEGORIES].sort((a, b) =>
    a.title.localeCompare(b.title, 'tr')
  );
};
